backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "blog-post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Featured Post", name: "featuredpost", widget: "boolean"}
      - {label: "Featured Image", name: "featuredimage", widget: image}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "list"}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "index-page"}
          - {label: Image, name: image, widget: image}
          - {label: Title, name: title, widget: string}
          - {label: Sous_titre, name: subheading, widget: string}
          - {label: Bouton, name: button, widget: object, fields: [{label: Texte, name: text, widget: string}, {label: Url, name: url, widget: string}]}
          - {label: Main, name: main, widget: object, fields: [{label: Petit_titre, name: littleTitle, widget: string},{label: Gros_titre, name: bigTitle, widget: string},{label: Description, name: description, widget: text},{label: Chiffre, name: chiffre, widget: object, fields: [{label: Numero, name: number, widget: string},{label: Details, name: details,widget: string }]}]}
          - {label: Vignettes, name: blocs, widget: object, fields: [{label: Carre, name: carre, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Certifications, name: certifications, widget: list, fields: [{label: Image, name: image, widget: image}]}
          - {label: Valeurs, name: values, widget: list, fields: [{label: Titre, name: title, widget: string}]}
          - {label: Temoignages, name: whitnesses, widget: list, fields: [{label: Nom, name: name, widget: string},{label: Text, name: text, widget: text}]}
          - {label: Contacts, name: contacts, widget: list, fields: [{label: Icon, name: icon, widget: image},{label: Titre, name: title, widget: string},{label: Details, name: details, widget: text}]}
      - file: "src/pages/about/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
      - file: "src/pages/products/index.md"
        label: "Products Page"
        name: "products"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-page"}
          - {label: Title, name: title, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: Heading, name: heading, widget: string}
          - {label: Description, name: description, widget: string}
          - {label: Intro, name: intro, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Blurbs, name: blurbs, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Text, name: text, widget: text}]}]}
          - {label: Main, name: main, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: text}, {label: Image1, name: image1, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image2, name: image2, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}, {label: Image3, name: image3, widget: object, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}]}
          - {label: Testimonials, name: testimonials, widget: list, fields: [{label: Quote, name: quote, widget: string}, {label: Author, name: author, widget: string}]}
          - {label: Full_image, name: full_image, widget: image}
          - {label: Pricing, name: pricing, widget: object, fields: [{label: Heading, name: heading, widget: string}, {label: Description, name: description, widget: string}, {label: Plans, name: plans, widget: list, fields: [{label: Plan, name: plan, widget: string}, {label: Price, name: price, widget: string}, {label: Description, name: description, widget: string}, {label: Items, name: items, widget: list}]}]}
      - file: "src/pages/amb/index.md"
        label: "AMB"
        name: "amb"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "amb-page"}
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [{label: Texte, name: text, widget: string}, {label: Url, name: url, widget: string}]}
      - file: "src/pages/social-media-management/index.md"
        label: "Social Média Management"
        name: "social-media-management"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/seo/index.md"
        label: "Référencement naturel (SEO)"
        name: "seo"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/events/index.md"
        label: "Agence évènementiel"
        name: "events"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/growth-driven-design/index.md"
        label: "Growth Driven Design"
        name: "growth-driven-design"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/agence-idendite-visuelle/index.md"
        label: "Agence Identite Visuelle"
        name: "agence-idendite-visuelle"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/sales-enablement/index.md"
        label: "Sales Enablement"
        name: "sales-enablement"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/content-marketing/index.md"
        label: "content Marketing"
        name: "content-marketing"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
      - file: "src/pages/marketing-automation/index.md"
        label: "Marketing Automation"
        name: "marketing-automation"
        fields:
          - { label: "Template Key", name: "templateKey", widget: "hidden", default: "social-media-management-page" }
          - { label: Image, name: image, widget: image }
          - { label: Title, name: title, widget: string }
          - { label: Sous_titre, name: subheading, widget: string }
          - { label: Image_contenu, name: inner_image, widget: image }
          - { label: Bouton, name: button, widget: object, fields: [ { label: Texte, name: text, widget: string }, { label: Url, name: url, widget: string } ] }
